name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle install --jobs 4 --retry 3

      - name: Build gem
        run: |
          gem build bullet_train-extensions.gemspec

      - name: Show built gem file
        run: |
          ls -l *.gem
